#!/bin/bash
fun1(){
  wget "https://raw.githubusercontent.com/EequMCC/shadowsocks/master/debian-install.sh" && chmod +x debian-install.sh && ./debian-install.sh
}

fun2(){
  wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubiBackup/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh
}

fun3(){
  wget https://raw.githubusercontent.com/EequMCC/V2ray/master/V2ray.sh && chmod +x V2ray.sh && ./V2ray.sh
}

fun4(){
  apt-get install ffmpeg
  wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
  chmod a+rx /usr/local/bin/youtube-dl
  wget --no-check-certificate https://raw.githubusercontent.com/EequMCC/some-script/master/yc
  chmod +x yc && mv yc /usr/bin
}

echo "[1]Shadowsocks [2]ShadowsocksR [3]V2ray [4]Youtube-dl"
read -p "Please Select(Default All):" a
if [[ "$a" == *1* ]];then
  fun1
fi
if [[ "$a" == *2* ]];then
  fun2
fi
if [[ "$a" == *3* ]];then
  fun3
fi
if [[ "$a" == *4* ]];then
  fun4
fi
if [ -z $a ];then
  fun1
  fun2
  fun3
  fun4
fi
