#!/bin/bash
if [ $1 == 1 ];then
	if [ $2 == 0 ];then
		youtube-dl -o "/home/%(title)s.%(ext)s" "$3"
	else
		youtube-dl -o "/home/%(title)s.%(ext)s" -f $2 "$3"
	fi
fi
if [ $1 == 2 ];then
	cd /home
	nohup python3 -m http.server &
fi
if [ $1 == 3 ];then
	youtube-dl -F "$3"
fi
if [ $1 == 4 ];then
	youtube-dl --get-id $3 >>id.txt
	n=1
	for i in id.txt
	do
		m+=1
	done
	while $n<=$m
	do
		id=${cat id.txt | sed -n ${n}p}
		youtube-dl -o "/home/%(title)s.%(ext)s" -f $2 $id
		n=n+1
	done
	rm id.txt
fi
