#!/bin/bash
if [ $1 == 1 ];then
	if [ $2 == 0 ];then
		youtube-dl -o "/home/%(title)s.%(ext)s" "$3"
	else
		youtube-dl -o "/home/%(title)s.%(ext)s" -f $2 "$3"
	fi
fi
if [ $1 == 2 ];then
	cd /home
	python3 -m http.server &
fi
if [ $1 == 3 ];then
	youtube-dl -F "$3"
fi
